services:

  homes:
    image: homeimage
    depends_on:
      - postgres
    container_name: homecontainer
    ports:
      - "3000:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__PostgreSQLConnection=Server=host.docker.internal;Port=5433;Database=housesdb;User Id=yo;Password=admin;
      - ASPNETCORE_URLS=http://+:80

  users:
    image: userimage
    depends_on:
      - mongo
    container_name: usercontainer
    ports:
      - "3001:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80

  gateway:
    image: gatewayimage
    container_name: gatewaycontainer
    ports:
      - "3030:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80

  email:
    image: emailimage
    container_name: emailcontainer
    ports:
      - "3002:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80

  postgres:
    container_name: postgres-sql
    image: postgres
    hostname: myfancyhost
    environment:
      POSTGRES_USER: yo
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: housesdb
      #DATABASE_HOST: 127.0.0.1
    volumes:
      - ~/Documentos/docker-vol/postgres-volume/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.1
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ~/Documentos/docker-vol/pgadmin-volume/data:/var/lib/pgadmin
    ports:
      - "5050:80"
    user: root
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

  mongo:
    image: mongo:4.4.25-focal
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["mongod", "--port", "27017"]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yo
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ~/Documentos/docker-vol/mongo-volume/data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yo
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_USER: 'yo'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - ~/Documentos/docker-vol/mysql-volume/data:/data/db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8065:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql


      

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: