// <auto-generated />
using System;
using Homes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Homes.Migrations
{
    [DbContext(typeof(HouseDb))]
    partial class HouseDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Homes.Models.Home", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<bool?>("AireAcondicionado")
                        .HasColumnType("boolean");

                    b.Property<string>("Ambiente")
                        .HasColumnType("text");

                    b.Property<string>("Antiguedad")
                        .HasColumnType("text");

                    b.Property<string>("ArmariosEmpotrados")
                        .HasColumnType("text");

                    b.Property<bool?>("Ascensor")
                        .HasColumnType("boolean");

                    b.Property<string>("Aseos")
                        .HasColumnType("text");

                    b.Property<string>("AutobusMasProximo")
                        .HasColumnType("text");

                    b.Property<string>("BajoOplantabaja")
                        .HasColumnType("text");

                    b.Property<string>("Balcon")
                        .HasColumnType("text");

                    b.Property<bool?>("Calefaccion")
                        .HasColumnType("boolean");

                    b.Property<string>("Calle")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<string>("Condicion")
                        .HasColumnType("text");

                    b.Property<int?>("Cp")
                        .HasColumnType("integer");

                    b.Property<string>("Creador")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Descuento")
                        .HasColumnType("text");

                    b.Property<string>("Disponibilidad")
                        .HasColumnType("text");

                    b.Property<string>("DistanciaAlMar")
                        .HasColumnType("text");

                    b.Property<string>("Duracion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<int?>("EstanciaMinima")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Fianza")
                        .HasColumnType("integer");

                    b.Property<string>("Garage")
                        .HasColumnType("text");

                    b.Property<string>("Gastos")
                        .HasColumnType("text");

                    b.Property<string>("Habitaciones")
                        .HasColumnType("text");

                    b.Property<int?>("HabitantesActualmente")
                        .HasColumnType("integer");

                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("InstalacionesDiscapacitados")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Internet")
                        .HasColumnType("boolean");

                    b.Property<string>("Jardin")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<bool?>("Mascotas")
                        .HasColumnType("boolean");

                    b.Property<string>("MetroMasProximo")
                        .HasColumnType("text");

                    b.Property<string>("NuevoProyecto")
                        .HasColumnType("text");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroVisitas")
                        .HasColumnType("text");

                    b.Property<string>("PanelesSolares")
                        .HasColumnType("text");

                    b.Property<bool?>("Parquet")
                        .HasColumnType("boolean");

                    b.Property<string>("PerfilCompartir")
                        .HasColumnType("text");

                    b.Property<string>("Piscina")
                        .HasColumnType("text");

                    b.Property<string>("PrecioFinal")
                        .HasColumnType("text");

                    b.Property<string>("PrecioInicial")
                        .HasColumnType("text");

                    b.Property<bool?>("PropietarioviveEnlacasa")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SeadmitenMenoresdeedad")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SeadmitenParejas")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SepuedeFumar")
                        .HasColumnType("boolean");

                    b.Property<string>("Superficie")
                        .HasColumnType("text");

                    b.Property<string>("Terraza")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.Property<bool?>("Trastero")
                        .HasColumnType("boolean");

                    b.Property<string>("Video")
                        .HasColumnType("text");

                    b.Property<string>("VistasDespejadas")
                        .HasColumnType("text");

                    b.Property<string>("ViviendaId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });
#pragma warning restore 612, 618
        }
    }
}
